---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
plugins:
  phpcodesniffer:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
  sonar-php:
    enabled: true
ratings:
  paths:
  - "**.php"
exclude_paths:
- docs/*
- tests/*
