---
Name: HaveIBeenPwndConfig
---
Firesphere\HaveIBeenPwnd\Services\HaveIBeenPwndService:
  allow_pwnd: false
  save_pwnd: true
---
Only:
  environment: dev
---
Firesphere\HaveIBeenPwnd\Services\HaveIBeenPwndService:
  allow_pwnd: true
